---
apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: get-supported-ephemeral-cluster-versions
spec:
  description: >-
    This StepAction queries the hub cluster used to provision ephemeral clusters for testing.
    It returns a list of supported versions stored in a hypershift ConfigMap.
  image: quay.io/redhat-appstudio/appstudio-utils@sha256:586149e3f18d966f681d956ab074b4e1d8433663d615ed86e19a3804ba952dfe
  params:
    - name: kubeconfigSecretLabelSelector
      type: string
      default: toolchain.dev.openshift.com/spacerequest=eaas
      description: A label selector used to identify the secret containing the EaaS hub cluster kubeconfig
    - name: insecureSkipTLSVerify
      type: string
      default: "false"
      description: Skip TLS verification when accessing the EaaS hub cluster
  env:
    - name: LABEL_SELECTOR
      value: "$(params.kubeconfigSecretLabelSelector)"
    - name: INSECURE_SKIP_TLS_VERIFY
      value: "$(params.insecureSkipTLSVerify)"
  results:
    - name: versions
      type: array
      description: List of supported minor versions from newest to oldest. E.g. ["4.15","4.14","4.13"]
  script: |
    #!/bin/bash
    set -eo pipefail

    TMP_KUBECONFIG=$(mktemp)
    trap 'rm "$TMP_KUBECONFIG"' EXIT

    oc get secret -l $LABEL_SELECTOR -o jsonpath="{.items[0].data.kubeconfig}" | base64 -d > $TMP_KUBECONFIG
    OC=(oc --insecure-skip-tls-verify=$INSECURE_SKIP_TLS_VERIFY --kubeconfig=$TMP_KUBECONFIG)

    SV=$(${OC[*]} get configmap supported-versions -n hypershift -o=jsonpath='{.data.supported-versions}')
    VERSIONS=$(echo "$SV" | jq -c '.versions')
    echo "Supported versions: $VERSIONS"
    echo -n "$VERSIONS" > $(step.results.versions.path)
