---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "appstudio, hacbs"
  name: clair-scan
spec:
  params:
    - name: image-digest
      description: Image digest to scan
    - name: image-url
      description: Url to image
    - name: docker-auth
      description: folder with config.json for container auth
      default: ""
  results:
    - name: HACBS_TEST_OUTPUT
      description: test output
    - name: CLAIR_SCAN_RESULT
      description: clair scan result
  steps:
    - name: get-vulnerabilities
      image: quay.io/redhat-appstudio/clair-in-ci:latest  # explicit floating tag, daily updates
      imagePullPolicy: Always
      env:
        - name: DOCKER_CONFIG
          value: $(params.docker-auth)
        - name: IMAGE_URL
          value: $(params.image-url)
        - name: IMAGE_DIGEST
          value: $(params.image-digest)
      script: |
        #!/usr/bin/env bash

        imagewithouttag=$(echo $IMAGE_URL | sed "s/\(.*\):.*/\1/" | tr -d '\n')
        # strip new-line escape symbol from parameter and save it to variable
        imageanddigest=$(echo $imagewithouttag@$IMAGE_DIGEST)

        clair-action report --image-ref=$imageanddigest --db-path=/tmp/matcher.db --format=quay > /tekton/home/clair-result.json || true
    - name: conftest-vulnerabilities
      image: quay.io/redhat-appstudio/hacbs-test:v1.0.10@sha256:ae276785973aaffb4554c1798cf629df33e7058b30c32b75bd8ada54b2afe42f
      securityContext:
        capabilities:
          add:
            - SETFCAP
      script: |
        if [ ! -s /tekton/home/clair-result.json ]; then
          echo "Previous step [get-vulnerabilities] failed, /tekton/home/clair-result.json is empty."
        else
          /usr/bin/conftest test --no-fail /tekton/home/clair-result.json \
          --policy /project/clair/vulnerabilities-check.rego --namespace required_checks \
          --output=json | tee /tekton/home/clair-vulnerabilities.json || true
        fi
    - name: test-format-result
      image: quay.io/redhat-appstudio/hacbs-test:v1.0.10@sha256:ae276785973aaffb4554c1798cf629df33e7058b30c32b75bd8ada54b2afe42f
      script: |
        #!/usr/bin/env bash
        . /utils.sh

        if [[ ! -f /tekton/home/clair-vulnerabilities.json ]] || [[ "$(jq '.[] | has("failures")' /tekton/home/clair-vulnerabilities.json)" == "false" ]]; then
          HACBS_TEST_OUTPUT=$(make_result_json -r "ERROR" -t "/tekton/home/clair-vulnerabilities.json is not generated correctly, please check again")
          echo "/tekton/home/clair-vulnerabilities.json is not generated correctly, please check again"
          echo "${HACBS_TEST_OUTPUT}" | tee $(results.HACBS_TEST_OUTPUT.path)
          exit 0
        fi

        jq -rce \
          '{vulnerabilities:{
              critical: (.[] | .failures | map(select(.metadata.details.name=="clair_critical_vulnerabilities")) | length),
              high: (.[] | .failures | map(select(.metadata.details.name=="clair_high_vulnerabilities")) | length),
              medium: (.[] | .failures | map(select(.metadata.details.name=="clair_medium_vulnerabilities")) | length),
              low: (.[] | .failures | map(select(.metadata.details.name=="clair_low_vulnerabilities")) | length)
            }}' /tekton/home/clair-vulnerabilities.json | tee $(results.CLAIR_SCAN_RESULT.path)

        HACBS_TEST_OUTPUT=$(make_result_json -r "SUCCESS" -t "Please refer to result CLAIR_SCAN_RESULT for the vulnerabilities scanned by clair")
        echo "${HACBS_TEST_OUTPUT}" | tee $(results.HACBS_TEST_OUTPUT.path)
